package drools.spring.rules;
dialect  "mvel"

import ftn.sbz.cdssserver.model.Patient;
import ftn.sbz.cdssserver.model.medicine.Medicine;
import ftn.sbz.cdssserver.model.medicine.Ingredient;
import ftn.sbz.cdssserver.model.rules.PossibleAllergies;

import java.util.List;


query checkAllergies(Patient p)
    $medAllergens: List() from accumulate (
        $meds: Medicine(this memberOf p.getAllergensMedicines()),
        collectList($meds)
    )
    $ingAllergens: List() from accumulate (
        $ings: Ingredient(this memberOf p.getAllergensIngredients()),
        collectList($ings)
    )
end