package drools.spring.rules;
dialect  "mvel"

import ftn.sbz.cdssserver.model.monitoring.MonitoringPatient;
import ftn.sbz.cdssserver.service.MonitoringService;
import ftn.sbz.cdssserver.model.monitoring.OxygenLevel;
import ftn.sbz.cdssserver.model.monitoring.HeartBeat;
//import ftn.sbz.cdssserver.model.monitoring.Urination;

import java.util.List;
import org.springframework.messaging.simp.SimpMessagingTemplate;

global SimpMessagingTemplate messagingTemplate;

/**
● Problem sa kiseonikom:
   o Nivo kiseonika u krvi pacijenta je manja od 70 mmHg
   o U poslednjih 15 minuta nisu zabeleženi događaji rasta nivoa kiseonika.
**/
rule "oxygen problems"
agenda-group "monitoring"
    when
        $monitoringPatient: MonitoringPatient(oxygenLevel != null, oxygenLevel.level < 70)
        // List(size == 0) from collect
        not ( OxygenLevel(patient == $monitoringPatient, growth == true) over window:time(15m) )
    then
        String message = "\nOxy problems for " + $monitoringPatient.getPatient().getName();
        System.out.println(message);
//        messagingTemplate.convertAndSend("/monitoring", message); // doesn't work in tests
end

/**
● Ubrzan srčani ritam:
o U poslednjih 10 sekundi zabeleženo više od 25 otkucaja srca
**/
rule "heart problems"
agenda-group "monitoring"
    when
        $monitoringPatient: MonitoringPatient()
        List(size > 25) from collect (
            HeartBeat(patient == $monitoringPatient) over window:time(10s)
        )
    then
        String message = "\nHeart problems for " + $monitoringPatient.getPatient().getName();
        System.out.println(message);
        //        messagingTemplate.convertAndSend("/monitoring", message); // doesn't work in tests
end





/**
● Hitno potrebna dijaliza:
o Pacijent boluje od hronične bubrežne bolesti
o U poslednjih 10 sekundi zabeleženo više od 10 otkucaja srca
o Suma količine mokrenja u poslednjih 12 sati je manja od 100ml
**/
