package drools.spring.rules;
dialect  "mvel"

import ftn.sbz.cdssserver.model.monitoring.MonitoringPatient;
import ftn.sbz.cdssserver.service.MonitoringService;

global MonitoringService monitoringService;

/** TEST **/
rule "monitoring"
    when
        MonitoringPatient($name: patient.name)
    then
        System.out.println("PATIENT " + $name + " ON MONITORING!");
end
/** TEST **/

//rule "oxygen problems"
//    when
//        MonitoringPatient($name: patient.name, oxygenLevel.level < 70)
//    then
//        System.out.println("\nOxy < 70 for " + $name);
//end
/**
Problema sa kiseonikom:
o Nivo kiseonika u krvi pacijenta je manja od 70 mmHg
o U poslednjih 15 minuta nisu zabeleženi događaji rasta nivoa kiseonika.
● Ubrzan srčani ritam:
o U poslednjih 10 sekundi zabeleženo više od 25 otkucaja srca
● Hitno potrebna dijaliza:
o Pacijent boluje od hronične bubrežne bolesti
o U poslednjih 10 sekundi zabeleženo više od 10 otkucaja srca
o Suma količine mokrenja u poslednjih 12 sati je manja od 100ml
**/
