package drools.spring.rules;
dialect  "mvel"

import ftn.sbz.cdssserver.model.Patient;
import ftn.sbz.cdssserver.model.Treatment;
import ftn.sbz.cdssserver.model.sickness.Sickness;
import ftn.sbz.cdssserver.model.medicine.Medicine;
//import ftn.sbz.cdssserver.model.
//import ftn.sbz.cdssserver.model.

import java.util.List;
import java.util.Set;
import java.util.HashSet;

/**
● Spisak pacijenata sa mogući hroničnim oboljenjima:
    o Pacijent je u poslednje dve godine više od 5 puta lečen od iste bolesti
    o Bolest nije prehlada ili groznica
**/
query chronicallySickPatients()
    $p: Patient() // over window:time(10s)
    $s: Sickness($name: name) over window:time(10s)
    List(size > 5) from collect (
        Treatment(patient == $p, sickness == $s, sickness.name != "Cold", sickness.name != "Fever")
        over window:time(730)
    )
end


/**
● Spisak mogućih zavisnika:
    o Pacijentu su u poslednjih 6 meseci barem 6 puta prepisani analgetici od strane 3 ili više različita
lekara
**/
query addicts()
    $p: Patient()
    $treatments: List(size >= 6) from collect (
        Treatment(patient == $p, this.hasAnalgetics()) over window:time(180d)
    )
    // three different doctors prescribed analgetics
    $d: List(size >= 3) from accumulate (
        Treatment($doctor: doctor) from $treatments,
        init(Set doctorsSet = new HashSet();),
        action(doctorsSet.add($doctor);),
        result(doctorsSet)
    )
end
/**
● Spisak pacijenta sa oslabljenim imunitetom:
    o Pacijent je lečen više od 10 puta u poslednjih 12 meseci od barem 2 različite bolesti za koje su mu
prepisani antibiotici
    o Pacijent u poslednjih 12 meseci nije bolovao od bolesti za koju mu nisu bili prepisani antibiotic
**/